/* Prix-Choc location compatibility: Arabic UI/data -> Sawa9ly French labels. */
(function(root,factory){ if(typeof module==='object'&&module.exports) module.exports=factory(); else root.PrixChocLocations=factory(); })(typeof globalThis!=='undefined'?globalThis:this,function(){
  const WILAYA_FR_BY_CODE={
    '01':'Adrar','02':'Chlef','03':'Laghouat','04':'Oum El Bouaghi','05':'Batna','06':'Béjaïa','07':'Biskra','08':'Béchar','09':'Blida','10':'Bouira','11':'Tamanrasset','12':'Tébessa','13':'Tlemcen','14':'Tiaret','15':'Tizi Ouzou','16':'Alger','17':'Djelfa','18':'Jijel','19':'Sétif','20':'Saïda','21':'Skikda','22':'Sidi Bel Abbès','23':'Annaba','24':'Guelma','25':'Constantine','26':'Médéa','27':'Mostaganem','28':"M'Sila",'29':'Mascara','30':'Ouargla','31':'Oran','32':'El Bayadh','33':'Illizi','34':'Bordj Bou Arreridj','35':'Boumerdès','36':'El Tarf','37':'Tindouf','38':'Tissemsilt','39':'El Oued','40':'Khenchela','41':'Souk Ahras','42':'Tipaza','43':'Mila','44':'Aïn Defla','45':'Naâma','46':'Aïn Témouchent','47':'Ghardaïa','48':'Relizane','49':'Timimoun','50':'Bordj Badji Mokhtar','51':'Ouled Djellal','52':'Béni Abbès','53':'In Salah','54':'In Guezzam','55':'Touggourt','56':'Djanet','57':"El M'Ghair",'58':'El Meniaa'
  };
  const SPECIAL={
    'شلاتة':'Chellata','الاربعاء':'Larbaa','الأربعاء':'Larbaa','أولاد يعيش':'Ouled Yaich','بني مراد':'Beni Mered','بني تامو':'Beni Tamou','عين الرمانة':'Ain Romana','عين وسارة':'Ain Oussara','عين معبد':'Ain Maabed','عين فكرون':'Ain Fakroun','عين مليلة':"Ain M'Lila",'عين البيضاء':'Ain Beida','عين أمقل':'Ain Amguel','عين صالح':'In Salah','عين قزام':'In Guezzam','عين تموشنت':'Ain Temouchent','عين الدفلى':'Ain Defla','عين تادلس':'Ain Tedles','أولاد أحمد تيمي':'Ouled Ahmed Timmi','زاوية كنتة':'Zaouiet Kounta','إن زغمير':'In Zghmir','اقبلي':'Akabli','تيمقتن':'Timekten','تسابيت':'Tsabit','تامست':'Tamest','تامنطيط':'Tamantit','تيدكلت':'Tit','السبع':'Sebaa','أريس':'Arris','مروانة':'Merouana','رأس العيون':'Ras El Aioun','تازولت':'Tazoult','المعذر':'El Madher','سريانة':'Seriana','القنطرة':'El Kantara','أولاد سلام':'Ouled Selam','أولاد سي سليمان':'Ouled Si Slimane','بني فضالة الحقانية':'Beni Foudhala El Hakania','فم الطوب':'Foum Toub','عيون العصافير':'Ayoune El Assafir','جرمة':'Djerma','وادي الماء':'Oued El Ma','حيدوسة':'Hidoussa','بوزينة':'Bouzina','تالخمت':'Talkhamt','الرحبات':'Rahbat','القصبات':'El Kasbat','زانة البيضاء':'Zana El Beida','وادي الطاقة':'Oued Taga','بريكة':'Barika','أولاد راشد':'Ouled Rached','المريرة':'El Meridja'
  };
  const WILAYA_AR_TO_CODE={
    'أدرار':'01','الشلف':'02','الأغواط':'03','أم البواقي':'04','باتنة':'05','بجاية':'06','بسكرة':'07','بشار':'08','البليدة':'09','البويرة':'10','تمنراست':'11','تبسة':'12','تلمسان':'13','تيارت':'14','تيزي وزو':'15','الجزائر':'16','الجلفة':'17','جيجل':'18','سطيف':'19','سعيدة':'20','سكيكدة':'21','سيدي بلعباس':'22','عنابة':'23','قالمة':'24','قسنطينة':'25','المدية':'26','مستغانم':'27','المسيلة':'28','معسكر':'29','ورقلة':'30','وهران':'31','البيض':'32','إليزي':'33','برج بوعريريج':'34','بومرداس':'35','الطارف':'36','تندوف':'37','تيسمسيلت':'38','الوادي':'39','خنشلة':'40','سوق أهراس':'41','تيبازة':'42','ميلة':'43','عين الدفلى':'44','النعامة':'45','عين تموشنت':'46','غرداية':'47','غليزان':'48','تيميمون':'49','برج باجي مختار':'50','أولاد جلال':'51','بني عباس':'52','عين صالح':'53','عين قزام':'54','تقرت':'55','جانت':'56','المغير':'57','المنيعة':'58'
  };
  for(const [ar,code] of Object.entries(WILAYA_AR_TO_CODE)){ if(WILAYA_FR_BY_CODE[code]) SPECIAL[ar]=WILAYA_FR_BY_CODE[code]; }
  SPECIAL['وادي سلي']='Oued Sly'; SPECIAL['أقبو']='Akbou'; SPECIAL['مشدالله']="M'Chedallah"; SPECIAL['ذراع الميزان']='Draâ El Mizan'; SPECIAL['ذراع بن خدة']='Draâ Ben Khedda'; SPECIAL['بوغني']='Boghni'; SPECIAL['عزازقة']='Azazga'; SPECIAL['تيقزيرت']='Tigzirt'; SPECIAL['فريحة']='Fréha'; SPECIAL['مقلع']='Mekla'; SPECIAL['معاتقة']='Maatkas'; SPECIAL['بني يني']='Beni Yenni'; SPECIAL['واقنون']='Ouaguenoun'; SPECIAL['واسيف']='Ouacif'; SPECIAL['إغيل علي']='Ighil Ali'; SPECIAL['خراطة']='Kherrata'; SPECIAL['صدوق']='Seddouk'; SPECIAL['سيدي عيش']='Sidi Aïch'; SPECIAL['أوزلاقن']='Ouzellaguen'; SPECIAL['برباشة']='Barbacha'; SPECIAL['بوخليفة']='Boukhelifa'; SPECIAL['بوحمزة']='Bouhamza'; SPECIAL['تازمالت']='Tazmalt'; SPECIAL['تامقرة']='Tamokra'; SPECIAL['تيزي نبربر']="Tizi N'Berber"; SPECIAL['ذراع القايد']='Draâ El Kaïd'; SPECIAL['لفلاي']='Leflaye'; SPECIAL['أدكار']='Adekar';
  function norm(v){return String(v??'').normalize('NFKC').replace(/[\u200B-\u200F\u202A-\u202E\u2060\uFEFF]/g,'').replace(/\s+/g,' ').trim();}
  function strip(v){return norm(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’'`]/g,'').replace(/[.,_\-/]/g,' ').replace(/\s+/g,' ').trim();}
  function arabicToLatin(value){
    const raw=norm(value);
    const direct=SPECIAL[raw]||SPECIAL[strip(raw)]; if(direct) return direct;
    const lexical={'أولاد':'Ouled','اولاد':'Ouled','بني':'Beni','عين':'Ain','وادي':'Oued','سيدي':'Sidi','برج':'Bordj','قصر':'Ksar','سوق':'Souk','أم':'Oum','ام':'Oum','بئر':'Bir','راس':'Ras','رأس':'Ras','الجزائر الوسطى':'Alger Centre','باب الزوار':'Bab Ezzouar','الرويبة':'Rouiba','الشراقة':'Cheraga','بئر خادم':'Birkhadem','بئر مراد رايس':'Bir Mourad Raïs','بن عكنون':'Ben Aknoun','الأبيار':'El Biar','حيدرة':'Hydra','القبة':'Kouba','حسين داي':'Hussein Dey','برج الكيفان':'Bordj El Kiffan','برج البحري':'Bordj El Bahri','دار البيضاء':'Dar El Beida','باب الوادي':'Bab El Oued','القصبة':'Casbah','وادي قريش':'Oued Koriche','بولوغين':'Bologhine','دالي إبراهيم':'Dely Ibrahim','عين البنيان':'Ain Benian','سطاوالي':'Staoueli','سيدي فرج':'Sidi Fredj','بابا حسن':'Baba Hassen','العاشور':'El Achour','الدرارية':'Draria','بئر توتة':'Bir Touta','براقي':'Baraki','الحراش':'El Harrach','وادي السمار':'Oued Smar','الرغاية':'Reghaïa','عين طاية':'Aïn Taya','المرسى':'El Marsa','زرالدة':'Zeralda','تيمياوين':'Timiaouine','الواتة':'El Ouata','القنادسة':'Kenadsa','تاغيت':'Taghit','كرزاز':'Kerzaz','بني ونيف':'Beni Ounif','لحمر':'Lahmar','مريجة':'Meridja','موغل':'Mogheul','بوكايس':'Boukais','تبلبالة':'Tabelbala','تيمودي':'Timoudi','قصابي':'Ksabi','أولاد خضير':'Ouled Khoudir','تامترت':'Tamtert','زغامرة':'Zghamra'};
    if(lexical[raw]) return lexical[raw];
    const map={'ا':'a','أ':'a','إ':'i','آ':'a','ٱ':'a','ب':'b','ت':'t','ث':'th','ج':'dj','ح':'h','خ':'kh','د':'d','ذ':'dh','ر':'r','ز':'z','س':'s','ش':'ch','ص':'s','ض':'d','ط':'t','ظ':'dh','ع':'a','غ':'gh','ف':'f','ق':'q','ك':'k','ل':'l','م':'m','ن':'n','ه':'h','و':'ou','ي':'i','ى':'a','ة':'a','ء':'','ؤ':'ou','ئ':'i','ڨ':'g','گ':'g'};
    let s=''; for(const ch of raw){s+=map[ch]??ch;}
    s=s.replace(/\bal\s*/gi,'El ').replace(/\boulad\b/gi,'Ouled').replace(/\bbni\b/gi,'Beni').replace(/\bain\b/gi,'Ain').replace(/\boued\b/gi,'Oued').replace(/\bsidi\b/gi,'Sidi').replace(/\bbordj\b/gi,'Bordj').replace(/\bqsr\b/gi,'Ksar');
    s=s.replace(/\bEl\s+/gi,'El ').replace(/\bOu\s+/gi,'Ou ');
    return s.replace(/\s+/g,' ').trim();
  }
  function wilayaCode(value){const n=strip(value); if(/^\d{1,2}$/.test(n)) return String(Number(n)).padStart(2,'0'); for(const [ar,code] of Object.entries(WILAYA_AR_TO_CODE)){if(strip(ar)===n)return code;} return null;}
  function wilayaFrench(value){const code=wilayaCode(value); return code?WILAYA_FR_BY_CODE[code]:String(value||'');}
  return {WILAYA_FR_BY_CODE,WILAYA_AR_TO_CODE,arabicToLatin,wilayaCode,wilayaFrench,norm,strip};
});

